### ISSUE TITLE
HA 2022.12 color scheme not inherited, still using paper-item-icon-active-color

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#95]
As title, the template-entity-row can not be set to inherit the new color schemes, see below for an example using the new binary-color which colors blue when on https://github.com/home-assistant/frontend/blob/3c8c1260b172cb2ef01328070e1c900b2cd3d4dc/src/resources/ha-style.ts#L145

in this case the top entity (unmodded, only needs `state_color: true`)
the bottom speaks for itself, the active is also set, but it takes

`paper-item-icon-active-color: gold` from the theme I set before the new color schemes were introduced.

```
  - type: entities
    state_color: true
    entities:
      - binary_sensor.ha_dev_update_available

      - type: custom:template-entity-row
        entity: binary_sensor.ha_dev_update_available
        name: >
          {% if states[config.entity] is not none %}
          {{state_attr(config.entity,'friendly_name').split(': Update Available')[0]}}
          {% else %} Initializing
          {% endif %}
        state: >
          {% if states[config.entity] is not none %}
            {{iif(states(config.entity) == 'on','Update available','Up to date')}}
          {% else %} Waiting for state
          {% endif %}
        secondary: >
          {% if states[config.entity] is not none %}
            {% set id = states[config.entity].object_id.split('_update_available')[0] %}
            {% if states['sensor.' + id + '_newest_version'] is not none %}
            New: {{states('sensor.' + id + '_newest_version')}} -
            {% endif %}Current:
            {{states('sensor.' + id + '_version')}}
          {% else %} Initializing
          {% endif %}
        active: >
          {{is_state(config.entity,'on')}}
```

<img width="522" alt="Scherm­afbeelding 2022-12-09 om 16 09 51" src="https://user-images.githubusercontent.com/33354141/206732674-f086c20f-91f7-45aa-8e8d-c6efabf1f881.png">

taking out paper color from the theme, leaves us with:

<img width="508" alt="Scherm­afbeelding 2022-12-09 om 16 14 27" src="https://user-images.githubusercontent.com/33354141/206733695-18c45d21-1faf-43a8-a598-c884174d7e47.png">

even though the more info is correctly showing the blue:

<img width="560" alt="Scherm­afbeelding 2022-12-09 om 16 15 18" src="https://user-images.githubusercontent.com/33354141/206733789-7079ab6c-748f-415f-89eb-600acf704544.png">

to be 100% certain it isnt an issue with the config.entity var, I also tried        

```
active: >
    {{is_state('binary_sensor.ha_dev_update_available','on')}}
```

lastly, when taking out the full t-e-r config, and only leaving the auto-entities section

```
  - type: custom:auto-entities
    card:
      type: entities
      title: Binaries update available
      card_mod:
        class: class-header-margin
      state_color: true
    show_empty: false
    filter:
      include:
        - entity_id: binary_sensor.*_update_available
          state: 'on'
#           options:
#             type: custom:template-entity-row
#             name: >
#               {% if states[config.entity] is not none %}
#               {{state_attr(config.entity,'friendly_name').split(': Update Available')[0]}}
#               {% else %} Initializing
#               {% endif %}
#             state: >
#               {% if states[config.entity] is not none %}
#                 {{iif(states(config.entity) == 'on','Update available','Up to date')}}
#               {% else %} Waiting for state
#               {% endif %}
#             secondary: >
#               {% if states[config.entity] is not none %}
#                 {% set id = states[config.entity].object_id.split('_update_available')[0] %}
#                 {% if states['sensor.' + id + '_newest_version'] is not none %}
#                 New: {{states('sensor.' + id + '_newest_version')}} -
#                 {% endif %}Current:
#                 {{states('sensor.' + id + '_version')}}
#               {% else %} Initializing
#               {% endif %}
#             active: >
#               {{is_state(config.entity,'on')}}
```

the blue is shown alright:

<img width="505" alt="Scherm­afbeelding 2022-12-09 om 16 23 31" src="https://user-images.githubusercontent.com/33354141/206735282-276ca73e-648b-46f4-bc99-e42e02781c42.png">

independent from the paper color. so it is the t-e-r preventing the inheritance of the new color scheme

btw, exchanging 
```
#   paper-item-icon-color: var(--primary-color)
  state-icon-color: '#636B75'
```
doesnt make a difference, in this case the state-icon-color is used, and still not the supposed binary color

**Comment by alexives** [comment]
I think this is related to #94, I tried replacing `light.` in the js with `binary_sensor.` and that seems to have fixed it on my instance. I put up #96 that I think should fix this.

**Comment by Mariusthvdb** [comment]
just adding another example here:

```
type: entities
state_color: true
entities:

  - type: custom:fold-entity-row
    head:
      type: section
      label: Batterij & verbinding
#     group_config:
#       state_color: true

    entities:
      - sensor.master_bedroom_hygro_temp_battery # <--- ok
      - type: custom:template-entity-row
        entity: sensor.master_bedroom_hygro_temp_battery # <--- not colored 
```

the `state_color: true` is working correctly for the regular entity inside the fold, and can even be colored using that option in the top entities card. Also works fine when used as fold option `group_config:`.

Does Not work inside the template-entity-row. 

<img width="517" alt="Scherm­afbeelding 2022-12-15 om 09 20 14" src="https://user-images.githubusercontent.com/33354141/207808569-44f5efa1-36ec-49d7-b13e-ec94ded51bef.png">

**Comment by keeema** [comment]
I face the same issue.

```
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:state-machine
    name: '{{ state_attr(''sensor.st_ems_device_info'', ''hybirdWorkMode'') }}'
  - type: custom:template-entity-row
    icon: >-
      {{ is_state('sensor.electricity_settings_gridconnectedunbalancedswitch',
      'True') | iif('mdi:scale-unbalanced','mdi:scale-balance') }}
    name: >-
      Invertor v {{
      is_state('sensor.electricity_settings_gridconnectedunbalancedswitch',
      'True') | iif('asymetrickém','symetrickém') }} režimu sítě {{
      is_state('sensor.electricity_settings_gridconnectedunbalancedswitch',
      'True') | iif('','!') }}
    active: >-
      {{ is_state('sensor.electricity_settings_gridconnectedunbalancedswitch',
      'True') }}
```

In all cases there is highlighted icon.
![image](https://user-images.githubusercontent.com/8296695/210406015-6693f2bb-996b-4de0-94bd-3babb1ddb0a4.png)

**Comment by ildar170975** [comment]
Before 2022.12:
The “—paper-item-icon-active-color” variable was used for all domains to represent an “active” state.

After 2022.12:
Different domains got their own variables for an “active” state. 
The list of these variables is NOT documented. 
Dev person promised to document them, so far it is not done.
Format of these new variables changed TWICE within last month:
— first they were of “255,255,255” format,
— then I asked “why using this format instead of traditional hex/rgb/names” - the Dev guy did not give a clear explanation and refused to change;
— then these variables were silently changed back to a traditional format by this Dev guy. 

IMHO, in this unpredictable situation with undocumented variables it is not easy to implement an old logic for an “active” state.

**Comment by chemelli74** [comment]
If can be of any help, this is the list I found on the `devs_frontend ` [discord's channel](https://discord.com/):

```
  state-default-color: '#44739E' # Default (Slate-Grey)
  state-alarm-armed-color: '#F44336' # Red
  state-alarm-arming-color: '#FF9800' # Orange
  state-alarm-disarmed-color: '#4CAF50' # Green
  state-alarm-pending-color: '#FF9800' # Orange
  state-alarm-triggered-color: '#F44336' # Red
  state-alert-color: '#F44336' # Red
  state-automation-color: '#FFC107' # Amber
  state-binary-sensor-alerting-color: '#F44336' # Red
  state-binary-sensor-color: '#FFC107' # Amber
  state-calendar-color: '#FFC107' # Amber
  state-camera-color: '#FFC107' # Amber
  state-climate-auto-color: '#4CAF50' # Green
  state-climate-cool-color: '#2196F3' # Blue
  state-climate-dry-color: '#FF9800' # Orange
  state-climate-fan-only-color: '#00BCD4' # Cyan
  state-climate-heat-color: '#FF5722' # Deep Orange
  state-climate-heat-cool-color: '#FFC107' # Amber
  state-climate-idle-color: '#8A8A8A' # Off (Mid-Grey)
  state-cover-color: '#9C27B0' # Purple
  state-fan-color: '#00BCD4' # Cyan
  state-group-color: '#FFC107' # Amber
  state-humidifier-color: '#2196F3' # Blue
  state-input-boolean-color: '#FFC107' # Amber
  state-light-color: '#FFC107' # Amber
  state-lock-jammed-color: '#F44336' # Red
  state-lock-locked-color: '#4CAF50' # Green
  state-lock-pending-color: '#FF9800' # Orange
  state-lock-unlocked-color: '#F44336' # Red
  state-media-player-color: '#03A9F4' # Light Blue
  state-person-home-color: '#4CAF50' # Green
  state-person-not-home-color: '#9E9E9E' # Grey
  state-person-zone-color: '#2196F3' # Blue
  state-remote-color: '#FFC107' # Amber
  state-script-color: '#FFC107' # Amber
  state-sensor-battery-high-color: '#4CAF50' # Green
  state-sensor-battery-low-color: '#F44336' # Red
  state-sensor-battery-medium-color: '#FF9800' # Orange
  state-sensor-battery-unknown-color: '#8A8A8A' # Off (Mid-Grey)
  state-siren-color: '#F44336' # Red
  state-sun-day-color: '#FFC107' # Amber
  state-sun-night-color: '#673AB7' # Deep Purple
  state-switch-color: '#FFC107' # Amber
  state-timer-color: '#FFC107' # Amber
  state-update-color: '#4CAF50' # Green
  state-update-installing-color: '#FF9800' # Orange
  state-vacuum-color: '#009688' # Teal
```

Simone

**Comment by ildar170975** [comment]
It may be changed any time.

**Comment by bcutter** [comment]
My main issue:

Using `custom:template-entity-row` for information (fake) entities with explicit `active: false` ... full example:

```
      - type: custom:template-entity-row
        name: Nur ausgewählte
        secondary: (wichtige, letzte Stunde)
        icon: mdi:information
        active: false
```

... now gives
![grafik](https://user-images.githubusercontent.com/13799156/211220406-8ce6a287-4d52-4615-9de5-90b9fa38d876.png)

I have now way to overwrite `--paper-item-icon-active-color` or (the here relevant) `--state-icon-active-color` using `style` or even `card_mod` according to https://developers.home-assistant.io/blog/2022/12/07/entity-color-changes/.

**I think this integration needs to fix this.** So finally an `active: false` starting HA Core 2022.12 won't look like a `active: true` like before HA Core 2022.12 anymore.

**Comment by emufan** [comment]
> I have now way to overwrite `--paper-item-icon-active-color` or (the here relevant) `--state-icon-active-color` using `style` or even `card_mod`

Do you mean now or no? If no, this is wrong, you can do it with card_mod:

```
  - type: custom:template-entity-row
    name: Nur ausgewählte
    secondary: (wichtige, letzte Stunde)
    icon: mdi:information
    active: false
    card_mod:
      style:
        state-badge:
          $: |
            ha-state-icon { color: red !important;}
```

**Comment by bcutter** [comment]
"No", updated the typo. Thanks for that snippet. I had exactly that styling - except the `!important`, which does the trick here.

Anyway, using `active: true|false` is still useless, which is the main issue for me.

**Comment by chadbaldwin** [comment]
@bcutter I don't know if this is helpul. But after a bunch of tinkering, this is what I was able to come up with and it works:

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Switches
  show_header_toggle: false
  state_color: true # doesn't actually do anything, but leaving it in just to keep around for troubleshooting
filter:
  include:
    - domain: switch
      options:
        type: custom:template-entity-row
        toggle: true
        active: '{{ is_state(config.entity, ''on'') }}'
        name: |
          {{
            state_attr(config.entity, 'friendly_name')
              | replace(' - Switch', '')
          }}
        card_mod:
          style: |
            :host {
              --paper-item-icon-active-color: #FFC107;
            }
  exclude:
    - state: unavailable
sort:
  method: entity_id
```

![image](https://user-images.githubusercontent.com/16479446/212182068-1c6ea815-ab31-43a7-9ffb-95ca204d75ca.png)

It's able to dymamically populate the card with a list of switch entities

It respects the `active:` property.

It works on both browser and mobile app (android).

The only thing I found to be problematic is for other entity types. For example, I have another similar card for battery entities. The default state colors are green, yellow, red to indicate battery level. Since there is logic behind the scenes to decide which color to show...you would have to build that in as some sort of template. I'm not sure if card-mod supports templates, but maybe that's an option.

I personally don't want to deal with that, so I'm just leaving it for now.

**Comment by Mariusthvdb** [comment]
sure card_mod does support templates, we can do:
```
      - type: custom:template-entity-row
        entity: sensor.master_bedroom_hygro_temp_battery
        <<: &config
          card_mod:
            style: |
              :host {
                --paper-item-icon-color:
                    {% set state = states(config.entity)|float(0) %}
                    {% if state > 75 %} green
                    {% elif state > 50 %} gold
                    {% elif state > 25 %} orange
                    {% elif state > 10 %} brown
                    {% else %} red
                    {% endif %};
                }
          name: >
            {% if states[config.entity] is not none %}
            {% set id = state_attr(config.entity,'friendly_name').split('hygro')[0] %}
            {{id}}
            {% else %} Initialiseren
            {% endif %}
          state: >
            {{states(config.entity)}} %
          secondary: >
            {% set id = config.entity.split('_battery')[0] %}
            Signal: {{states(id + '_signal_strength')}} dBm
      - type: custom:template-entity-row
        entity: sensor.dorm_hygro_temp_battery
        <<: *config
      - type: custom:template-entity-row
        entity: sensor.library_hygro_temp_battery
        <<: *config
```

but that is besides the point really.
Still hope template entity row could be set to use the colors set by the `entity` it uses, if it uses it.

**Comment by adi90x** [comment]
@chadbaldwin  : Is it still working with latest HA version 2023.2 ? As I don't seems to be able to force any colors on my icons

**Comment by TheHolyRoger** [comment]
@Mariusthvdb what happens if you set the `entity` parameter in your card config to a binary sensor?

**Comment by Mariusthvdb** [comment]
I have that:
```
      - type: custom:template-entity-row
        entity: binary_sensor.ha_dev_update_available
        name: >
          {% if states[config.entity] is not none %}
          {{state_attr(config.entity,'friendly_name').split(': Update Available')[0]}}
          {% else %} Initializing
          {% endif %}
        state: >
          {% if states[config.entity] is not none %}
            {{iif(states(config.entity) == 'on','Update available','Up to date')}}
          {% else %} Waiting for state
          {% endif %}
        secondary: >
          {% if states[config.entity] is not none %}
            {% set id = states[config.entity].object_id.split('_update_available')[0] %}
            {% if states['sensor.' + id + '_newest_version'] is not none %}
            New: {{states('sensor.' + id + '_newest_version')}} -
            {% endif %}Current:
            {{states('sensor.' + id + '_version')}}
          {% else %} Initializing
          {% endif %}
        active: >
          {{is_state(config.entity,'on')}}
```

**Comment by TheHolyRoger** [comment]
@Mariusthvdb so what is the custom theme colour you have? Is it `state-binary_sensor-update-on-color` or `state-update-active-color` ?

It would make sense if I just need to add another css class to the icon like `state-<DEVICE_CLASS>-active-color` which would then give it the `state-update-active-color` class?

**Comment by Mariusthvdb** [comment]
I have them both set.
```
    state-binary_sensor-update-on-color: red #'#f44336'
    state-update-active-color: red #'#f44336'
```

which does color the core Ha entity as you can see above.

I can try to also add
```
state-binary_sensor-update-active-color: red #'#f44336'
```
....

**Comment by TheHolyRoger** [comment]
@Mariusthvdb sorry I meant that I need to add those as css classes in the plugin

**Comment by Mariusthvdb** [comment]
Ah I see well, yes, maybe ;-)

fwiw:
Inspector on the t-e-r icon:

<img width="297" alt="Scherm­afbeelding 2023-03-14 om 10 17 34" src="https://user-images.githubusercontent.com/33354141/224954014-fdd77f1a-49f5-481d-94c4-5be8dd5d4c82.png">

and on the binary:

<img width="576" alt="Scherm­afbeelding 2023-03-14 om 10 18 03" src="https://user-images.githubusercontent.com/33354141/224954136-b7a79a5b-c42e-44a8-bb55-97d79b2b05ef.png">

**Comment by TheHolyRoger** [comment]
@Mariusthvdb I've just pushed an update, do you want to try 1.4.1? You need to clear cache manually.

I've done two things - first is to add the domain to the variable it uses internally and the second is I've added a new parameter: `device_class`

Based on your info it looks like for you this would work `device_class: update` keeping your existing theme changes.

Without that it will use the domain of the entity which for you is `state-binary_sensor-active-color`  (without the update) - unfortunately I can't fetch the device class without the user specifying in config

**Comment by Mariusthvdb** [comment]
are you saying we need to ad a device_class on all of our configs then? what would that do for non class entities, like eg an automation... 
hope I am not being too critical here, but fixing it only for update isnt really a solution

**Comment by TheHolyRoger** [comment]
@Mariusthvdb sorry was just in the middle of a quick fix for `sensor` entities.

You only need to add a `device_class` if you're using a custom device_class based rule in your theme config.

Otherwise it will use the entity's domain which is `binary_sensor` in your case.

I've fixed it for everyone whilst giving you a solution for your specific use-case ;)

It won't pick up any `on-color` variants, only `active` ones.

**Comment by Mariusthvdb** [comment]
thanks, you're doing a wonderful job, appreciated! 

and yet.... it nags this card now no longer follows core HA inner workings. As you said, we now need to set the device_class if we have colors set in our themes. These are not available for all themed domains though. And we now need to set 'active' in stead of 'on'.
Personally I found the latter to be unintuitive, and I like to follow the actual state of the domain. Could adapt there ofc, as 'active' might even be more encompassing (think group here, which is not always on/off, but can also be home/not_home..

Yet, I'd love t-e-r to follow core coloring schematics, so even though we now have your hacked card, hope Thomas can talk to Paul someday and fix this correctly ;-)

**Comment by TheHolyRoger** [comment]
You don't need to set `device_class` unless you're using device class based theme colours, if you're using only domain based colours it will pick these variables up automatically.

I'm following https://github.com/home-assistant/frontend/blob/1a9b9da0db5678890a4306ec412e6cdee1e6a27d/src/resources/ha-style.ts#L174 as a reference so not sure what you mean about "no longer follows core HA inner workings"

There are only a few 'on' colour rules defined for various binary sensor warning colours: https://github.com/home-assistant/frontend/blob/1a9b9da0db5678890a4306ec412e6cdee1e6a27d/src/resources/ha-style.ts#L139

"fix this correctly" rubbed me the wrong way a bit so I probably won't follow this thread anymore. Best of luck.

**Comment by Mariusthvdb** [comment]
no need to be defensive, all I meant was that I hoped Thomas would fix this in his own repo. 

the fact your fix requires

>  don't need to set device_class unless you're using device class based theme colours

is the extra setting, and hence not the same behavior  like the core cards, which do use the colors set for device_class in the themes. 

those 'on' colors are the former 'alert' class  domains, and yes, these are important ofc.

Having said that, yours is a much appreciated effort, and does fix a lot of situations.

**Comment by TheHolyRoger** [comment]
Please look closely at the variable names which end with `on-color`:

https://github.com/home-assistant/frontend/blob/1a9b9da0db5678890a4306ec412e6cdee1e6a27d/src/resources/ha-style.ts#L138

Your custom `on-color` variables above do not conform to the current HA style syntax. `on-color` is used for situational warnings and not device_class's e.g. `warning`, `gas`, `moisture`, `problem`.

To conform to HA syntax your variable should be one of the following:

- `state-update-active-color` (requires setting device_class parameter as explained above)
- `state-binary_sensor-active-color`


I understand your issue with setting the `device_class` config option, I don't know if I can retrieve the device class in lovelace as I've not done that before. It's something I can look into but perhaps after you stop claiming I'm not following HA inner workings when it's the reverse.

**Comment by Mariusthvdb** [comment]
my 'on' colors follow https://www.home-assistant.io/integrations/frontend/ correctly.

> The color rules can be customized using theme variables:
> 
> state-{domain}-{device_class}-{state}-color
> state-{domain}-{state}-color
> state-{domain}-(active|inactive)-color
> state-(active|inactive)-color

this was introduced after https://community.home-assistant.io/t/2022-12-color-states-are-broken-unusable/499890 was raised and frontend devs allowed coloring according to that schedule.

 be aware that we have binary_sensor entities with a `device_class: update` using the `state-binary_sensor-update` colors,(defaulting to the regular `state-binary_sensor` colors if not set),  and  update entities, using the `state-update` colors.

**Comment by TheHolyRoger** [comment]
@Mariusthvdb alright fair enough I get you now. I just pushed an update that hopefully follows those rules and will use device class first if available.

I removed the `device_class` option as it's available through the entity attributes which I didn't realise before.

Should hopefully use `on` css rules if the current state is either `true` or `On`

**Comment by Mariusthvdb** [comment]
really sorry to report that 
```
      - type: custom:template-entity-row
        entity: binary_sensor.ha_dev_update_available
        device_class: update
```
or without `device_class: update`

still dont show the themed color. 

the resource is loaded alright:

<img width="543" alt="Scherm­afbeelding 2023-03-14 om 16 59 33" src="https://user-images.githubusercontent.com/33354141/225063242-15e56752-9ced-4221-aa02-4dbd5f87f976.png">

and tested on both Safari and Chrome Mac browsers, obviously refreshed cache.

**Comment by Mariusthvdb** [comment]
looks a bit different in my Chrome inspector but this is it:

<img width="960" alt="Scherm­afbeelding 2023-03-14 om 17 10 02" src="https://user-images.githubusercontent.com/33354141/225067974-6b3735a6-0e49-4ea4-a25d-bfee23834f3c.png">

**Comment by TheHolyRoger** [comment]
@Mariusthvdb I think I can see the problem there... I was using the state of the template entity for the css check instead of the state of the underlying entity.

Try v1.4.4 and see if it fixes it, it will need the `active` config option to be set

**Comment by Mariusthvdb** [comment]
thats more like it:

<img width="973" alt="Scherm­afbeelding 2023-03-14 om 17 31 23" src="https://user-images.githubusercontent.com/33354141/225073503-6c2534a1-12e5-4842-81ff-781cb9c5c0a8.png">


to the right, there's also another card, using auto-entities to filter available updates.

**Comment by TheHolyRoger** [comment]
Cool :) so is it working as intended with your css rules?

**Comment by Mariusthvdb** [comment]
have to give it some test, but as far as I can see now, I have 3 domains indeed following the theme colors I set

**Comment by TheHolyRoger** [comment]
Good stuff 👍 opened a PR now, we'll see if it passes Thomas' standards ;)

**Comment by Mariusthvdb** [comment]
Just noticed there was a new release, with changes to the icon color .

Unfortunately, the this brings back the default color set in the core theme, and does not follow the theme variables set in custom themes:

```
    state-binary_sensor-update-on-color: red #'#f44336'
    state-binary_sensor-active-on-color: red #'#f44336'
```

back to showing
<img width="516" alt="Scherm­afbeelding 2023-03-27 om 23 17 31" src="https://user-images.githubusercontent.com/33354141/228069373-1becc51d-d389-46f2-9285-299907040484.png">


while the more-info shows the color in the theme:

<img width="550" alt="Scherm­afbeelding 2023-03-27 om 23 20 20" src="https://user-images.githubusercontent.com/33354141/228069421-cdca17fd-c5b2-4d5b-89bb-0ddf481d1e0d.png">

**Comment by ildar170975** [comment]
Sorry, I do not understand the latest fix.
Please consider this code:
```
    type: entities
    entities:
      - entity: input_boolean.test_boolean
      - type: custom:template-entity-row
        entity: input_boolean.test_boolean
        name: test_boolean - active always
        active: true
```
![image](https://user-images.githubusercontent.com/71872483/230468342-34d7544f-a905-417b-8429-23f96591f489.png)
With even a default theme the 2nd row is supposed to be shown as "active" - which does not happen.

Using the latest card.
![image](https://user-images.githubusercontent.com/71872483/230468748-d24cb498-ac0f-420f-bcaa-a71063c2ef85.png)

**Comment by TheHolyRoger** [comment]
@ildar170975 @Mariusthvdb would you like to try my latest release to see if it fixes your issues?

https://github.com/TheHolyRoger/lovelace-template-entity-row/releases/tag/1.3.3

@thomasloven I've also rebased my PR if you want to merge it in

**Comment by Mariusthvdb** [comment]
Sure!
You're previous version already did... what did you change now?

**Comment by TheHolyRoger** [comment]
@Mariusthvdb i've just rebased it on top of thomas' latest changes and tidied some bits up - hopefully it should all work the same!

If you find it's broken for you, I moved the old release to 1.3.1rc1 in releases if you need to rollback

**Comment by Mariusthvdb** [comment]
before (using official release)

<img width="479" alt="Scherm­afbeelding 2023-04-07 om 21 28 52" src="https://user-images.githubusercontent.com/33354141/230666338-8b662ae1-22e5-4029-b22b-dcbd7bb2d010.png">

your 1.3.3:

<img width="490" alt="Scherm­afbeelding 2023-04-07 om 21 29 15" src="https://user-images.githubusercontent.com/33354141/230666369-890a6c2a-c2b1-4cf4-88a5-c55bfd90da5e.png">

cool. thx.

**Comment by TheHolyRoger** [comment]
Noice 👍 no worries

**Comment by Mariusthvdb** [comment]
Hey Holy,

can I ask something else? could it be feasible to have T-E-R follow the domain colors of eg `device_class: battery`  too?

currently I need to set a card mod like:

```
      - type: custom:template-entity-row
        entity: sensor.master_bedroom_hygro_temp_battery
        <<: &config
          card_mod:
            style:
              div#wrapper:
                state-badge $: |
                  ha-state-icon {
                    color:
                    {% set state = states(config.entity)|float(0) %}
                    {% if state > 75 %} green
                    {% elif state > 50 %} gold
                    {% elif state > 25 %} orange
                    {% elif state > 10 %} brown
                    {% else %} red
                    {% endif %};
                  }
          name: >
            {% if states[config.entity] is not none %}
            {% set id = state_attr(config.entity,'friendly_name').split('hygro')[0] %}
            {{id}}
            {% else %} Initialiseren
            {% endif %}
          state: >
            {{states(config.entity)}} %
          secondary: >
            {% set id = config.entity.split('_battery')[0] %}
            Signal: {{states(id + '_signal_strength')}} dBm
```

I use this because it is more granular than the core colors. Yet, I would love the T-E-R to be able to follow those core colors without anything further.
I ofc did set state_color:true on the entities card, and on the group_config of this fold, so that is not working.

Please have a look?

**Comment by TheHolyRoger** [comment]
@Mariusthvdb i've got some time in a few days, send me a PM on the forum to remind me if you can, or if you're on discord, telegram etc

**Comment by Mariusthvdb** [comment]
PM sent.

I did forget to mention that because of the move to state-icon-color in the previous update (of this resource) this card_mod now also works, targeting that element:
```
          card_mod:
            style: |
              :host {
                --state-icon-color:
                    {% set state = states(config.entity)|float(0) %}
                    {% if state > 75 %} green
                    {% elif state > 50 %} gold
                    {% elif state > 25 %} orange
                    {% elif state > 10 %} brown
                    {% else %} red
                    {% endif %};
                  }
```

**Comment by TheHolyRoger** [comment]
@Mariusthvdb good sir, do you wanna try the latest release?

https://github.com/TheHolyRoger/lovelace-template-entity-row/releases/tag/1.3.4

I realised it's actually a lot simpler to get the entity state colours :)

Make sure `entity` is pointing to the correct entity, leave the following fields blank: `active`, `color` and it should use the underlying entity colour correctly now.

**Comment by TheHolyRoger** [comment]
@thomasloven imo it's worth you trying out my version in your hass yourself with the above "problem" configs ;) my PR is still open and can be cleanly merged ;)

**Comment by Mariusthvdb** [comment]
did the update and can confirm the battery colors to be shown as per HA design:

<img width="481" alt="Scherm­afbeelding 2023-05-07 om 16 25 02" src="https://user-images.githubusercontent.com/33354141/236683447-f34cf29f-c675-4aa6-8e17-38025d906d09.png">

using:
```
      - type: custom:template-entity-row
        entity: sensor.master_bedroom_hygro_temp_battery
        <<: &config
#           card_mod:
#             style: |
#               :host {
#                 --state-icon-color:
#                     {% set state = states(config.entity)|float(0) %}
#                     {% if state > 75 %} green
#                     {% elif state > 50 %} gold
#                     {% elif state > 25 %} orange
#                     {% elif state > 10 %} brown
#                     {% else %} red
#                     {% endif %};
#                   }
          name: >
            {% if states[config.entity] is not none %}
            {% set id = state_attr(config.entity,'friendly_name').split('hygro')[0] %}
            {{id}}
            {% else %} Initialiseren
            {% endif %}
          state: >
            {{states(config.entity)}} %
          secondary: >
            {% set id = config.entity.split('_battery')[0] %}
            Signal: {{states(id + '_signal_strength')}} dBm
```

**Comment by alanmilinovic** [comment]
@TheHolyRoger why the PR is not merged? I guess it is not what @thomasloven is expecting or?
